/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StackRouteImport } from './routes/stack'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as LaboratorioRouteImport } from './routes/laboratorio'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ConstruoRouteImport } from './routes/construo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as ProjetosSlugRouteImport } from './routes/projetos.$slug'

const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratorioRoute = LaboratorioRouteImport.update({
  id: '/laboratorio',
  path: '/laboratorio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstruoRoute = ConstruoRouteImport.update({
  id: '/construo',
  path: '/construo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosSlugRoute = ProjetosSlugRouteImport.update({
  id: '/projetos/$slug',
  path: '/projetos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/construo': typeof ConstruoRoute
  '/contato': typeof ContatoRoute
  '/laboratorio': typeof LaboratorioRoute
  '/roadmap': typeof RoadmapRoute
  '/sobre': typeof SobreRoute
  '/stack': typeof StackRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/construo': typeof ConstruoRoute
  '/contato': typeof ContatoRoute
  '/laboratorio': typeof LaboratorioRoute
  '/roadmap': typeof RoadmapRoute
  '/sobre': typeof SobreRoute
  '/stack': typeof StackRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/projetos': typeof ProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/construo': typeof ConstruoRoute
  '/contato': typeof ContatoRoute
  '/laboratorio': typeof LaboratorioRoute
  '/roadmap': typeof RoadmapRoute
  '/sobre': typeof SobreRoute
  '/stack': typeof StackRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/construo'
    | '/contato'
    | '/laboratorio'
    | '/roadmap'
    | '/sobre'
    | '/stack'
    | '/projetos/$slug'
    | '/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/construo'
    | '/contato'
    | '/laboratorio'
    | '/roadmap'
    | '/sobre'
    | '/stack'
    | '/projetos/$slug'
    | '/projetos'
  id:
    | '__root__'
    | '/'
    | '/construo'
    | '/contato'
    | '/laboratorio'
    | '/roadmap'
    | '/sobre'
    | '/stack'
    | '/projetos/$slug'
    | '/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConstruoRoute: typeof ConstruoRoute
  ContatoRoute: typeof ContatoRoute
  LaboratorioRoute: typeof LaboratorioRoute
  RoadmapRoute: typeof RoadmapRoute
  SobreRoute: typeof SobreRoute
  StackRoute: typeof StackRoute
  ProjetosSlugRoute: typeof ProjetosSlugRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratorio': {
      id: '/laboratorio'
      path: '/laboratorio'
      fullPath: '/laboratorio'
      preLoaderRoute: typeof LaboratorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construo': {
      id: '/construo'
      path: '/construo'
      fullPath: '/construo'
      preLoaderRoute: typeof ConstruoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$slug': {
      id: '/projetos/$slug'
      path: '/projetos/$slug'
      fullPath: '/projetos/$slug'
      preLoaderRoute: typeof ProjetosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConstruoRoute: ConstruoRoute,
  ContatoRoute: ContatoRoute,
  LaboratorioRoute: LaboratorioRoute,
  RoadmapRoute: RoadmapRoute,
  SobreRoute: SobreRoute,
  StackRoute: StackRoute,
  ProjetosSlugRoute: ProjetosSlugRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
